---
title: "Influence of West Antarctic Ice Sheet collapse on Antarctic surface climate"
collection: publications
permalink: /publication/2015-06-01-WAIScollapse
excerpt: '<i>Abstract:</i> Climate model simulations are used to examine the impact of a collapse of the West Antarctic Ice Sheet (WAIS) on the surface climate of Antarctica. The lowered topography following WAIS collapse produces anomalous cyclonic circulation with increased flow of warm, maritime air toward the South Pole and cold-air advection from the East Antarctic plateau toward the Ross Sea and Marie Byrd Land, West Antarctica. Relative to the background climate, areas in East Antarctica that are adjacent to the WAIS warm, while substantial cooling (several ∘C) occurs over parts of West Antarctica. Anomalously low isotope-paleotemperature values at Mount Moulton, West Antarctica, compared with ice core records in East Antarctica, are consistent with collapse of the WAIS during the last interglacial period, Marine Isotope Stage 5e. More definitive evidence might be recoverable from an ice core record at Hercules Dome, East Antarctica, which would experience significant warming and positive oxygen isotope anomalies if the WAIS collapsed.'
date: 2015-06-01
venue: 'Geophysical Research Letters'
citation: 'Steig EJ, Huybers K, Singh HA, Steiger NJ, Ding Q, Frierson DMW, Popp T, White JWC. (2015). &quot;Influence of West Antarctic Ice Sheet collapse on Antarctic surface climate.&quot; <i>Geophysical Research Letters</i>. 42: pp 4862-4868.'
---

<i>Abstract:</i> Climate model simulations are used to examine the impact of a collapse of the West Antarctic Ice Sheet (WAIS) on the surface climate of Antarctica. The lowered topography following WAIS collapse produces anomalous cyclonic circulation with increased flow of warm, maritime air toward the South Pole and cold-air advection from the East Antarctic plateau toward the Ross Sea and Marie Byrd Land, West Antarctica. Relative to the background climate, areas in East Antarctica that are adjacent to the WAIS warm, while substantial cooling (several ∘C) occurs over parts of West Antarctica. Anomalously low isotope-paleotemperature values at Mount Moulton, West Antarctica, compared with ice core records in East Antarctica, are consistent with collapse of the WAIS during the last interglacial period, Marine Isotope Stage 5e. More definitive evidence might be recoverable from an ice core record at Hercules Dome, East Antarctica, which would experience significant warming and positive oxygen isotope anomalies if the WAIS collapsed.

[Download paper here](http://hansialice.github.io/files/GRL-SteigEtAl2015-WAIScollapse.pdf)
